services:
  - type: web
    name: projexiq-frontend
    runtime: static
    buildCommand: npm install && npm run build:prod
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.17.0 